#!/bin/bash
#
# The MIT License (MIT)
#
# Copyright (c) 2014 Lauri Võsandi
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

PATH="$PATH:/sbin"
NSSDB=$HOME/.pki/nssdb
MODUTIL="/usr/bin/modutil -force -dbdir sql:$NSSDB"
LIBS=$(/usr/sbin/ldconfig -v 2>/dev/null | /usr/bin/grep -v ^$'\t' | /usr/bin/sed -e s/:.*$//)
PKCS11=onepin-opensc-pkcs11.so

if [ ! -f "$NSSDB"/cert9.db ]; then
    echo "Initializing new database:"
    mkdir -p "$NSSDB"

fi

delete_pkcs11() {
    if $MODUTIL -list "$1" 2>>/dev/null; then
        $MODUTIL -delete "$1"
    fi
}

delete_pkcs11 "idemia-pkcs11"

for DIR in $LIBS; do
    LIB=$DIR/$PKCS11

    if [ -f "$LIB" ]; then
        echo "Found PKCS#11 library at: $LIB"

        if /usr/bin/grep -q -s library="$LIB" "$"NSSDB/pkcs11.txt; then
            echo "ID-card support for Google Chrome/Chromium is already enabled!"

        else
            echo "Enabling ID-card functionality for Google Chrome/Chromium via $LIB:"
            delete_pkcs11 "opensc-pkcs11"
            $MODUTIL -add opensc-pkcs11 -libfile "$LIB" -mechanisms FRIENDLY

        fi

        exit
    fi

done

echo "Can't find $PKCS11!"
