#!/bin/bash
#
# The MIT License (MIT)
#
# Copyright (c) 2014 Lauri Võsandi
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

NSSDB=$HOME/.pki/nssdb
MODUTIL="/usr/bin/modutil -force -dbdir sql:$NSSDB"
CERTUTIL="/usr/bin/certutil -d sql:$NSSDB"
LIB="/usr/lib/$(gcc -print-multiarch)"
PKCS_LIB=$LIB/onepin-opensc-pkcs11.so

if [ ! -f $NSSDB/cert9.db ]; then
    echo "Initializing new database"
    mkdir -p $NSSDB
    $CERTUTIL -N --empty-password
fi

echo "Adding Estonian ID-card certificates"
$CERTUTIL -A -t ",," -n "ESTEID-SK_2007" -i "/usr/share/esteid/certs/ESTEID-SK 2007.crt"
$CERTUTIL -A -t ",," -n "ESTEID-SK_2011" -i "/usr/share/esteid/certs/ESTEID-SK 2011.crt"

echo "Probing for PKCS#11 library"
if [ ! -f $PKCS_LIB ]; then
    echo "No OpenSC installed!"
    exit 0
fi
echo "Found: $PKCS_LIB"

if grep -q library=$PKCS_LIB $NSSDB/pkcs11.txt; then
    echo "ID-card support for Google Chrome/Chromium already enabled"
else
    # If onepin from OpenSC 0.12.x is present use it
    echo "Enabling ID-card functionality in Google Chrome/Chromium via $PKCS_LIB"
    $MODUTIL -delete opensc-pkcs11
    $MODUTIL -add opensc-pkcs11 -libfile $PKCS_LIB -mechanisms FRIENDLY
fi
